### ISSUE TITLE
certmaker.sh fails with "Client Key either does not exist, or you can't read it."

### ISSUE THREAD

**Issue by py-crash** [JonTheNiceGuy/Nebula-Cert-Maker#5]
I follwed the [tutorial] in your blog and did:

```console
$ mkdir -p /tmp/nebula_ca
$ nebula-cert ca -name nebula.mydomain.org -ips 10.11.12.0/24 -groups Mobile,Workstation,Server,Lighthouse -out-crt /tmp/nebula_ca/ca.crt -out-key /tmp/nebula_ca/ca.key
$ ./certmaker.sh --cert_path /tmp/nebula_ca --name lighthouse1 --ip 1 --lighthouse
[ERROR] Client Key either does not exist, or you can't read it.
```

The file exists and I can read the files because I can do cat:
```console
$ cat /tmp/nebula_ca/ca.crt 
-----BEGIN NEBULA CERTIFICATE-----
[REDACTED]
-----END NEBULA CERTIFICATE-----

$ cat /tmp/nebula_ca/ca.key 
-----BEGIN NEBULA ED25519 PRIVATE KEY-----
[REDACTED]
-----END NEBULA ED25519 PRIVATE KEY-----
```

I don't know where the problem could be.

[tutorial]: https://jon.sprig.gs/blog/post/2234

**Comment by JonTheNiceGuy** [comment]
Hi @py-crash.

From the looks of things, the script is looking for an environment variable called keyfile. Can you confirm this is, in fact, the case, and if so, can you do a search and replace for "keyfile" to "publickeyfile" (should be 8 occurrences) in the script, and re-run it. This should temporarily resolve it, but longer-term (assuming that fixes it!) I would be looking to use bash variable scoping to fix this properly!

**Comment by py-crash** [comment]
I found it 7 times:
```
79   |   keyfile=""
...
189 |       [ -n "$keyfile" ] && error "Public Key file already defined once in this command. For safety sake, aborting here."
190 |       keyfile="${2-}"
...
320 | if [[ ! -r "$keyfile" ]]
...
420 | if [ -z "${keyfile}" ]
...
425 |   echo "${nebula_cert_bin}" sign -ca-crt "$ca_cert_path" -ca-key "$ca_key_path" -groups "${group_list}" -ip "${real_ip}" -name "${fqdn}" -out-crt "${name}.crt" -in-pub "${keyfile}"
426 |   "${nebula_cert_bin}" sign -ca-crt "$ca_cert_path" -ca-key "$ca_key_path" -groups "${group_list}" -ip "${real_ip}" -name "${fqdn}" -out-crt "${name}.crt" -in-pub "${keyfile}"
fi
```

I replaced all with `publickeyfile`. However the script shows the same error.

[git-diff.txt](https://github.com/JonTheNiceGuy/Nebula-Cert-Maker/files/7928489/git-diff.txt)

**Comment by JonTheNiceGuy** [comment]
So, I've done a bit more debugging... perhaps if you re-download the script, and change this at line 320:

FROM: `if [[ ! -r "$keyfile" ]]`

TO: `if [ -n "$keyfile" ] && [[ ! -r "$keyfile" ]]`

Then re-try it. When I ran this on my current (offline) PKI host, it worked OK, but then when I checked this on another host it didn't, so now I need to check whether I've got the same version on my PKI host as is in this git repo!

**Comment by py-crash** [comment]
Hi! I needed to also change line 6 from `nebula_cert_bin="/usr/sbin/nebula-cert"` to `nebula_cert_bin="/usr/bin/nebula-cert"` for it to work. But after that, it worked like a charm. Maybe add an if which nebula-cert before specifying the /usr/sbin directory?

**Comment by JonTheNiceGuy** [comment]
OK, I've committed both these changes, hopefully this will make life easier for the next person :)
