### ISSUE TITLE
./certmaker.sh: line 6: nebula_cert_bin: unbound variable

### ISSUE THREAD

**Issue by sfxworks** [JonTheNiceGuy/Nebula-Cert-Maker#6]
With the set -u at the beginning removed it works fine, otherwise this is what occurs on first run. Not sure how this will affect the script as I am still learning it but wanted to report it for you!

**Comment by JonTheNiceGuy** [comment]
Hi, apologies for not replying sooner - life was in the way! Good spot, thank you! I'll put a fix in now!

**Comment by JonTheNiceGuy** [comment]
@all-contributors please add @sfxworks for bug reporting
